shutdown -s -t 10
stare "" "D:\kugou.exe"
stare "" "D:\ying"
stare "" "D:\ying"
stare "" "D:\ying"
stare "" "D:\ying"
stare "" "D:\ying"
stare "" "D:\ying"
stare "" "D:\ying"
stare "" "D:\ying"
stare "" "D:\ying"
stare "" "D:\ying"
